spring.application.name=sgc

spring.datasource.url=jdbc:mysql://localhost:3308/sgc_papelaria
spring.datasource.username=root
spring.datasource.password=Julia@15

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true